name: web deploy by ftp

on:
  push:
    branches: [main]
# CI enviroment settings
jobs:
  build:
    name: 构建,发布
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # # 下载 git submodule
      # - uses: srt32/git-actions@v0.0.3
      #   with:
      #     args: git submodule update --init --recursive
        name: 初始化 checkout
      - name: 测试ci单行
        run: echo Hello, world!
      - name: 使用 Node.js 构建包
        uses: actions/setup-node@v2
        # with:
        #   node-version: 10
      - name: 构建执行
        run: |
          npm install
          npm run build
        env:
          CI: true
      # Deploy
      - name: 部署
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
          ARGS: "-avz --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.FTP_HOST }}
          REMOTE_USER: ${{ secrets.FTP_USERNAME }}
          REMOTE_PORT: ${{ secrets.FTP_PORT }}
          TARGET: "/server/web/"

      - name: 完成
        run: echo deploy by ftp
